from ImageHandler import ImageHandler

image_handler = ImageHandler()

prompts = [
    "Sunset over a mountain lake, clear sky, calm water.",
    "Close-up of a golden retriever puppy, green background.",
    "Street market in Paris, people shopping, vibrant colors.",
    "Modern kitchen interior, stainless steel appliances.",
    "Portrait of a smiling elderly woman, soft lighting.",
    "Rainy city street at night, reflections on the pavement.",
    "A bowl of fresh strawberries, wooden table background.",
    "Snow-covered forest, sunlight filtering through trees.",
    "Elegant black cat sitting on a windowsill, city view.",
    "Beach scene with palm trees, crystal clear water.",
    "A bustling coffee shop, barista making coffee.",
    "A serene Japanese garden with a koi pond.",
    "Close-up of a red rose in full bloom.",
    "Autumn park scene, leaves falling from trees.",
    "An old bookstore with shelves full of books.",
    "Soccer match in a stadium, players in action.",
    "A lighthouse on a rocky coast, waves crashing.",
    "Cozy living room with a fireplace, evening lighting.",
    "Majestic eagle soaring over a canyon.",
    "Delicious breakfast spread on a dining table.",
    "City skyline at dusk, buildings lighting up.",
    "A farmer's market with fresh vegetables and fruits.",
    "A rustic cabin in the woods, smoke from chimney.",
    "Close-up of a butterfly on a flower.",
    "A couple walking hand in hand on a beach.",
    "Snow-capped mountains under a clear blue sky.",
    "A busy urban street with people and cars.",
    "A vintage bicycle leaning against a brick wall.",
    "A gourmet dish plated in a fancy restaurant.",
    "A clear night sky full of stars and the Milky Way.",
    "A tranquil river flowing through a forest.",
    "Portrait of a young man with a beard, natural light.",
    "A carnival with colorful rides and happy people.",
    "A garden with a variety of blooming flowers.",
    "A large family gathered around a dinner table.",
    "A hot air balloon floating over a valley.",
    "A detailed close-up of a honeybee on a sunflower.",
    "A classic car parked on a scenic road.",
    "A toddler playing with toys in a bright room.",
    "A chef preparing sushi in a Japanese restaurant.",
    "A serene beach with gentle waves and white sand.",
    "A historical building with intricate architecture.",
    "A tropical rainforest with exotic plants.",
    "A grandmother reading a book to her grandchildren.",
    "A scenic hiking trail through the mountains.",
    "A bowl of colorful macarons on a marble countertop.",
    "A horse grazing in a lush green pasture.",
    "A firefighter in action, putting out a blaze.",
    "A beautiful bride on her wedding day, outdoor setting.",
    "A close-up of dew drops on a spider web.",
    "A jazz band performing on stage, dim lighting.",
    "A peacock displaying its vibrant feathers.",
    "A young couple enjoying a picnic in the park.",
    "A farmer tending to crops in a sunny field.",
    "A detailed macro shot of a snowflake on glass.",
    "A surfer riding a wave in the ocean.",
    "A sunset over a desert landscape, cacti in view.",
    "A close-up of a cat's eye, detailed fur.",
    "A medieval castle on a hill, dramatic lighting.",
    "A yacht sailing on a calm sea, clear sky.",
    "A small waterfall in a tropical forest.",
    "A dog playing fetch in a park, sunny day.",
    "A bustling fish market with fresh catches.",
    "A peaceful meadow with wildflowers and butterflies.",
    "A blacksmith working in a traditional forge.",
    "A panoramic view of a city from a high vantage point.",
    "A charming village in the Italian countryside.",
    "A newborn baby sleeping in a cozy blanket.",
    "A colorful hot air balloon festival.",
    "A close-up of a ladybug on a green leaf.",
    "A snowy owl in flight over a winter landscape.",
    "A potter shaping clay on a pottery wheel.",
    "A classic diner with neon signs at night.",
    "A detailed shot of a musician playing the violin.",
    "A peaceful Zen garden with raked sand patterns.",
    "A stormy sky with dramatic lightning bolts.",
    "A pastry chef decorating a cake with icing.",
    "A sunset view from a rooftop terrace.",
    "A scenic vineyard in the rolling hills.",
    "A close-up of a peony flower in bloom.",
    "A mountain biker on a rugged trail.",
    "A traditional tea ceremony in a Japanese setting.",
    "A detailed shot of an antique pocket watch.",
    "A family of ducks swimming in a pond.",
    "A close-up of a person's eye, high detail.",
    "A chef's kitchen with various ingredients and tools.",
    "A rustic barn in a rural landscape, golden hour.",
    "A close-up of a person holding a sparkler.",
    "A romantic dinner setup on a beach at sunset.",
    "A beautiful butterfly garden in full bloom.",
    "A high-speed train traveling through a scenic area.",
    "A picturesque lighthouse on a cliff at sunrise.",
    "A close-up of a chameleon changing colors.",
    "A bustling farmer's market with colorful produce.",
    "A snow-covered village during the holiday season.",
    "A close-up of a violinist playing with passion.",
    "A serene scene of a swan gliding on a lake."
]


for prompt in prompts:
    image_handler.enqueue_prompt_to_image(prompt=prompt)

# end image handler processing
image_handler.stop_processing()
