AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to generate IAM development user and administrator role

Parameters:
  devUserName:
    Type: String
    AllowedPattern: '[a-z0-9]+'
    Default: dev

Resources:
  devUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref devUserName
      # Login profile is configured manually after stack creation to avoid the use of AWS Secrets Manager
      # See SETUP.md for a guide!

  lambdaFullAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              AWS: !GetAtt devUser.Arn
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: LambdaFullAccessRole

  devUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref devUser
      Status: Active
  
Outputs:
  devUserAccessKeyId:
    Value: !Ref devUserAccessKey
  devUserAccessKeyPass:
    Value: !GetAtt devUserAccessKey.SecretAccessKey
  devUserName:
    Value: !Ref devUser
  lambdaFullAccessRoleArn:
    Value: !GetAtt lambdaFullAccessRole.Arn